version: "3.9"

services:
  db:
    profiles: ["app"]
    image: postgres:16
    container_name: tripplanner_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:    
    profiles: ["app"]
    image: ${APP_IMAGE:-victorzele96/trip_planner-app:latest}
    container_name: tripplanner_app
    restart: always
    env_file:
      - .env
    ports:
      - "${STREAMLIT_PORT:-8501}:${STREAMLIT_PORT:-8501}"
    depends_on:
      - db

  #DB Configuration
  test_db:
    profiles: ["tests"]
    image: postgres:16
    container_name: tripplanner_db_test
    env_file:
    - .env.test
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 2s
      retries: 10
      start_period: 5s

  tests:
    profiles: ["tests"]
    build: .
    container_name: tripplanner_tests
    env_file:
      - .env.test
    # ports:
    #   - "${STREAMLIT_PORT}:${STREAMLIT_PORT}"
    environment:
      PYTHONPATH: /trip_planner
    depends_on:
      test_db:
        condition: service_healthy
    working_dir: /trip_planner
    command: ["pytest", "--junitxml=/results/report.xml"]
    volumes:
    - ./reports:/results

volumes:
  pgdata:
  pgdata_test: